import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>人口推移</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title">人口推移を確認</h1>
    </div>
  );
}
